<a href="https://colab.research.google.com/github/IntroComputationalPhysics-UNT/more-on-numpy-Mattmflores/blob/main/more_on_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More on NumPy

We have used NumPy already, but there is more that you can do with it, and much of its function is useful in physics modeling. NumPy provides fast, _vectorized_ numerical computations using arrays.

## Review

**Evaluate the following cells**

In [ ]:
import numpy as np
np.__version__

'2.0.2'

In [ ]:
# explore NumPy
dir(np)[:20] # first 20 entries

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__']

In [ ]:
# get help for a specific function
help(np.sin)

Help on ufunc:

sin = <ufunc 'sin'>
    sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Trigonometric sine, element-wise.

    Parameters
    ----------
    x : array_like
        Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array will retain its original value.
        Note that if an uninitialized `out` array is created via the default
        ``

In [ ]:
# COMPLETE THIS TASK
# Find documentation for np.linspace using '?'
np.linspace?

## Creating Vectors and Matrices

### Creating vectors

In [ ]:
v1 = np.array([1, 2, 3])
v2 = np.linspace(0, 1, 5)
v3 = np.arange(0, 10, 2)
v1, v2, v3

(array([1, 2, 3]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([0, 2, 4, 6, 8]))

### Creating matrices

In [ ]:
A = np.array([[1, 2], [3, 4]])
Z = np.zeros((3,3))
I = np.eye(4)
A, Z, I

(array([[1, 2],
        [3, 4]]),
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]]))

### Indexing and slicing

In [ ]:
A[0, 1], A[:, 0], A[1]

(np.int64(2), array([1, 3]), array([3, 4]))

### Random matrices

In [ ]:
R = np.random.randn(3,3)
U = np.random.rand(3,3)
R, U

(array([[-1.48292177, -0.09175973, -0.8386707 ],
        [-0.36669135,  0.77312267,  1.0092256 ],
        [ 0.04343099, -1.37640305,  2.53011748]]),
 array([[0.90980656, 0.83638098, 0.07503352],
        [0.75745813, 0.49578694, 0.37066835],
        [0.66844461, 0.10782246, 0.26437521]]))

In [ ]:
# COMPLETE THIS TASK
# Decompose a 5×5 random matrix into (real) symmetric and antisymmetric parts.
# A symmetric matrix A satisfies A = 0.5*(A + A.T);
# An antisymmetric matrix satisfies A = 0.5*(A - A.T);
# The `.T` attribute finds the transpose of the matrix.
A = np.random.rand(5, 5)

A_sym = 0.5 * (A + A.T)
A_anti = 0.5 * (A - A.T)

A, A_sym, A_anti


(array([[0.54473966, 0.43785712, 0.40173086, 0.38730036, 0.52327499],
        [0.78064412, 0.2874602 , 0.29077498, 0.70382312, 0.9120014 ],
        [0.78796318, 0.61468656, 0.70055355, 0.72647486, 0.15795637],
        [0.32720939, 0.03455151, 0.48204826, 0.62042446, 0.03154677],
        [0.36615777, 0.39444734, 0.36783914, 0.14588562, 0.64825376]]),
 array([[0.54473966, 0.60925062, 0.59484702, 0.35725488, 0.44471638],
        [0.60925062, 0.2874602 , 0.45273077, 0.36918732, 0.65322437],
        [0.59484702, 0.45273077, 0.70055355, 0.60426156, 0.26289775],
        [0.35725488, 0.36918732, 0.60426156, 0.62042446, 0.0887162 ],
        [0.44471638, 0.65322437, 0.26289775, 0.0887162 , 0.64825376]]),
 array([[ 0.        , -0.1713935 , -0.19311616,  0.03004549,  0.07855861],
        [ 0.1713935 ,  0.        , -0.16195579,  0.3346358 ,  0.25877703],
        [ 0.19311616,  0.16195579,  0.        ,  0.1222133 , -0.10494138],
        [-0.03004549, -0.3346358 , -0.1222133 ,  0.        , -0.0571694

## Operations: *, @, and np.matmul / np.dot

Elementwise and matrix multiplication are treated differently in Numpy.

### Elementwise multiplication (`*`)

In [ ]:
A = np.array([[1,2],[3,4]])
B = np.array([[10,20],[30,40]])
A * B

array([[ 10,  40],
       [ 90, 160]])

### Matrix multiplication (`@`)

In [ ]:
A @ B

array([[ 70, 100],
       [150, 220]])

### Function equivalents for matrix multiplication

In [ ]:
np.matmul(A, B), np.dot(A, B)

(array([[ 70, 100],
        [150, 220]]),
 array([[ 70, 100],
        [150, 220]]))

In [ ]:
# COMPLETE THESE TASKS
# 1. look into the documentation for `np.matmul`, `np.dot`, `@`, and `*` and explain their difference(s)
# 2. create an example/examples to explain their differences

# *        → elementwise multiplication (Hadamard product)
# @        → matrix multiplication (A @ B)
# np.matmul → same as @ but works with batches of matrices
# np.dot    → for 2D arrays it's the same as @, but for 1D arrays it gives the inner product

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[10, 20],
              [30, 40]])

# Elementwise multiplication
print("A * B =\n", A * B)

# Matrix multiplication
print("\nA @ B =\n", A @ B)

# np.matmul
print("\nnp.matmul(A, B) =\n", np.matmul(A, B))

# np.dot (same as @ for 2D)
print("\nnp.dot(A, B) =\n", np.dot(A, B))

# 1D example to show np.dot difference
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])

print("\nv * w =", v * w)        # elementwise
print("np.dot(v, w) =", np.dot(v, w))  # inner product
print("v @ w =", v @ w)                  # same as dot for 1D



A * B =
 [[ 10  40]
 [ 90 160]]

A @ B =
 [[ 70 100]
 [150 220]]

np.matmul(A, B) =
 [[ 70 100]
 [150 220]]

np.dot(A, B) =
 [[ 70 100]
 [150 220]]

v * w = [ 4 10 18]
np.dot(v, w) = 32
v @ w = 32


## Vectorization and Performance

_Vectorization_ means applying operations to whole arrays at once, rather than element by element.

### Loop version -- one element at a time

In [ ]:
import math

In [ ]:
%%timeit
xs = np.linspace(0, 10, 1_000_000) # here the '_' is used as a visual seperator -- i.e. 1,000,000
ys_loop = np.zeros_like(xs)
for i in range(len(xs)):
  ys_loop[i] = math.sin(xs[i])

290 ms ± 6.11 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


### Vectorized version

In [ ]:
%%timeit
xs = np.linspace(0, 10, 1_000_000)
y_vec = np.sin(xs)

18.8 ms ± 3.13 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [ ]:
# COMPLETE THIS TASK
# ask Gemini about `%%timeit`

# The %%timeit is a Jupyter "cell magic" command used for timing the execution
# of a Python statement or an entire cell. It automatically runs the code
# multiple times (typically 100 or 10,000 times, depending on the execution time)
# and then reports the best and average execution time, along with the standard
# deviation. This helps in getting a more accurate and statistically sound measurement of the code's performance, especially for short-running operations, by mitigating the effects of system noise.


In [ ]:
# COMPLETE THIS TASK
# create a vectorized function that calculates the total energy (T+U; kinetic + potential energy) of a harmonic oscillator
def harmonic_energy(m, k, x, v):
    """
    Vectorized total energy of a harmonic oscillator.
    m, k: scalars
    x, v: arrays or scalars (broadcasted)
    """
    x = np.asarray(x)
    v = np.asarray(v)
    T = 0.5 * m * v**2
    U = 0.5 * k * x**2
    return T + U



## Eigenvalues and Eigenvectors

For a matrix $M$, eigenvalues $\lambda$ and eigenvectors $v$ satisfy:
$$ M v = \lambda v $$

In physics, these often realte to characteristic and measurable physical quantities:
* Oscillators → $\lambda$ relates to squared frequencies
* Quantum mechanics → $\lambda$ could be the energy eigenstates
* Rotations → $\lambda$ could define a principal axes

### Here is an example matrix

In [ ]:
K = np.array([[ 1,-1, 0]
             ,[-1, 2,-1]
             ,[ 0,-1, 1] ])
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([9.99658224e-17, 1.00000000e+00, 3.00000000e+00]),
 array([[-5.77350269e-01, -7.07106781e-01,  4.08248290e-01],
        [-5.77350269e-01,  9.71445147e-17, -8.16496581e-01],
        [-5.77350269e-01,  7.07106781e-01,  4.08248290e-01]]))

In [ ]:
# COMPLETE THIS TASK
# In the above cell, which eigenvector is associated with which eigenvalue?

# The i-th column vecs[:, i] is the eigenvector associated
# with eigenvalue vals[i].
# By definition of np.linalg.eigh:
# vals[0] ↔ vecs[:, 0]
# vals[1] ↔ vecs[:, 1]
# vals[2] ↔ vecs[:, 2]

for i, lam in enumerate(vals):
    print(f"Eigenvalue {i}: {lam}")
    print("  Eigenvector:", vecs[:, i])


Eigenvalue 0: 9.996582244115599e-17
  Eigenvector: [-0.57735027 -0.57735027 -0.57735027]
Eigenvalue 1: 1.0
  Eigenvector: [-7.07106781e-01  9.71445147e-17  7.07106781e-01]
Eigenvalue 2: 3.0
  Eigenvector: [ 0.40824829 -0.81649658  0.40824829]


## Quadratic Form: Diatomic Molecule Model

We can model a diatomic molecule (O$_2$ or N$_2$, for example) as two masses connected by a spring. Motion is restricted to the
bond axis.

The (quadratic) potential energy is: `V = 0.5 * x.T @ K @ x ` where `x = (x1, x2)`, the coordinates of the two atoms.

### Constructing a stiffness/force-constant matrix

In [ ]:
k = 2450 # the force constant in an appropriate [energy]/[length] units
K = np.array([[ k,-k]
             ,[-k, k]])
K

array([[ 2450, -2450],
       [-2450,  2450]])

### Diagonalize to find frequencies and normal mode displacement patterns

In [ ]:
vals, vecs = np.linalg.eigh(K)
vals, vecs

(array([   0., 4900.]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

### Vibrational frequencies (ignoring mass)

In [ ]:
omega = np.sqrt(vals)
omega

array([ 0., 70.])

### Unitary transformations with eigenvector matrices

If the matrix is not singular, we can find eigenvalues and eigenvectors. The matrix of eigenvectors $U$ forms a unitary transformation.

In [ ]:
# COMPLETE THESE TASKS
# Show that U@U.T and U.T@U are 2x2 identity matrices
# Note that normally we would need to use the `.conj().T` attribute to find the conjugate transpose matric, but our matrix is real.
U = vecs  # eigenvector matrix

print("U @ U.T =")
print(U @ U.T)

print("\nU.T @ U =")
print(U.T @ U)

# For an orthonormal eigenvector matrix U, both expressions
# should be (numerically) equal to the 2x2 identity matrix:
print("\nCheck closeness to identity:")
print(np.allclose(U @ U.T, np.eye(2)))
print(np.allclose(U.T @ U, np.eye(2)))


U @ U.T =
[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]

U.T @ U =
[[ 1.00000000e+00 -2.23711432e-17]
 [-2.23711432e-17  1.00000000e+00]]

Check closeness to identity:
True
True


In [ ]:
# COMPLETE THIS TASK
# From the eigenvalue equation M v = λ v, it follows that for U = [v1, v2], then M U = λ U.
# Because λ is diagonal and U.T@U = np.eye(2), it follows that λ = U.T @ K @ U.
# Confirm this behavior.
# K, vals, vecs already defined above
U = vecs
Lambda = np.diag(vals)        # diagonal matrix of eigenvalues

left = U.T @ K @ U            # should equal Lambda

print("Lambda =")
print(Lambda)
print("\nU.T @ K @ U =")
print(left)

print("\nCheck equality:")
print(np.allclose(left, Lambda))


Lambda =
[[   0.    0.]
 [   0. 4900.]]

U.T @ K @ U =
[[ 3.94430453e-31  6.65719202e-14]
 [-8.69285906e-14  4.90000000e+03]]

Check equality:
True


In [ ]:
# COMPLETE THIS TASK
# Use the eigenvectors to eigenvalues to interpret the two modes in this model of a diatomic molecule

# Mode 1: eigenvalue ≈ 0, eigenvector ~ (1, 1)
#   Both atoms move in phase by the same amount.
#   This is a center-of-mass motion,
#   so the bond length does not change and there is effectively no restoring force.

# Mode 2: eigenvalue ≈ 2k, eigenvector ~ (1, -1)
#   The two atoms move in opposite directions.
#   This changes the bond length, so it corresponds to the
#   stretching of the diatomic molecule.

for i, lam in enumerate(vals):
    print(f"Mode {i}: eigenvalue = {lam}, omega = {np.sqrt(lam)}")
    print("  eigenvector =", vecs[:, i])


Mode 0: eigenvalue = 0.0, omega = 0.0
  eigenvector = [-0.70710678 -0.70710678]
Mode 1: eigenvalue = 4900.0, omega = 70.0
  eigenvector = [-0.70710678  0.70710678]
